---
telegram:
  - identifier: group
    title: Официальная русскоязычная группа в Telegram
    name: Группа
    url: https://t.me/joinchat/AkuYY0ExBslQKlt2CRDazA
  - identifier: stickers
    title: Тематический набор стикеров
    name: Набор стикеров
    url: https://t.me/addstickers/TulpaWiki
discord:
  - identifier: general
    name: Сервер
    title: Официальный русскоязычный сервер в Discord
    url: https://discord.gg/aWfvuXf
partners:
  - identifier: tulpa_info
    name: Tulpa.info
    title: Главный интернациональный ресурс о феномене
    url: https://tulpa.info/
  - identifier: deskchan
    name: DeskChan
    title: Персональный цифровой ассистент с кастомизацией характера
    url: https://deskchan.info/
